pipeline {
    agent any
    stages {
        stage ('GIT Checkout'){
            steps {
                git branch: "main", changelog: false, poll: false, url: 'https://github.com/maxibra/6over6.git'
            }
        }

        stage ('Test'){
            steps {
                dir("app") {
                    sh 'python3 fibonacii_test.py'
                }
            }
        }
        stage('Building image') {
            steps{
                dir("app") {
                    script {
                        app = docker.build "maxib/fibonacii"
                    }
                }
            }
        }
        stage('Pushing Fibonachii image') {
            steps{
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docerio') {
                        app.push("latest")
                    }
                }
            }
        }
        stage('Deploying app') {
            steps{
                sshagent(credentials: ['ssh-app']) {
                    sh 'ssh vagrant@192.168.56.11 docker run -d -name app maxib/fibonacii'
                }
            }
    }


    post {
        always {
            echo 'One way or another, I have finished'
            cleanWs deleteDirs: true /* clean up our workspace */
        }
    }
}