pipeline {
    agent any
    stages {
        stage ('GIT Checkout'){
            steps {
                git branch: "main", changelog: false, poll: false, url: 'https://github.com/maxibra/6over6.git'
            }
        }

        stage ('Test'){
            steps {
                dir("app") {
                    sh 'python3 fibonacii_test.py'
                }
            }
        }

    }

    post {
        always {
            echo 'One way or another, I have finished'
            cleanWs deleteDirs: true /* clean up our workspace */
        }
    }
}